name: My CI

on:
  push:
    branches:
      - main


jobs:
  hello:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "Hello world"

  test:
    name: Run tests
    strategy:
      matrix:
        os: ["ubuntu-latest", "window-latest"]
        python-version: ['3.9', '3.10'] # no double quotes
        include:
          - os: 'macos-latest'
            python-version: '3.11'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5 # this is a comment
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "Running in ${{ matrix.os }} with Python ${{ matrix.python-version }}"
      - name: Only runs on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "This is Linux"
      - name: Install package
        run: pip install .[test]
      - name: Run Pytest
        run: python -m pytest -v


